import Navigation from '../components/navigation';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="kr">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
